### PR TITLE
Fixed Texture2D::Create(...)

### LINKED ISSUE #296: Fix Texture2D::Create(...)  to generate correct internal image buffer size
Texture2D struct has public APIs that help the creation of monochrome texture.
+ Create (uint32_t width, uint32_t height)
+ Create (uint32_t width, uint32_t height, float r, float g, float b, float a)

The current implementation of those methods uses a fixed buffer (`image_data`) that doesn't scale along the input parameters: width, height.

The fix should take care of dynamically scale and fill the buffer to correctly create the requested texture2D object

### PR DESCRIPTION
**Pull request by jnyfah**
closes #296

### CODE REVIEW

File: ZEngine/ZEngine/Rendering/Renderers/GraphicRenderer.cpp [hunk 1]
```diff
@@ -292,28 +292,39 @@ namespace ZEngine::Rendering::Renderers
...
+        size_t                     data_size = width * height * Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)];
+        std::vector<unsigned char> image_data(data_size);
 
-        Specifications::TextureSpecification spec = {.Width = width, .Height = height, .BytePerPixel = Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)], .Format = Specifications::ImageFormat::R8G8B8A8_SRGB, .Data = image_data};
+        unsigned char              r_byte = static_cast<unsigned char>(std::clamp(r * 255.0f, 0.0f, 255.0f));
+        unsigned char              g_byte = static_cast<unsigned char>(std::clamp(g * 255.0f, 0.0f, 255.0f));
+        unsigned char              b_byte = static_cast<unsigned char>(std::clamp(b * 255.0f, 0.0f, 255.0f));
+        unsigned char              a_byte = static_cast<unsigned char>(std::clamp(a * 255.0f, 0.0f, 255.0f));
+
+        for (size_t i = 0; i < data_size; i += Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)])
```
Comment (JeanPhilippeKernel) [inline ZEngine/ZEngine/Rendering/Renderers/GraphicRenderer.cpp]: please simplify the expression, Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)] 
by making the call once at the top

File: ZEngine/ZEngine/Rendering/Renderers/GraphicRenderer.cpp [hunk 2]
```diff
@@ -292,28 +292,39 @@ namespace ZEngine::Rendering::Renderers
...
     {
-        unsigned char                        image_data[] = {255, 255, 255, 255, '\0'};
-
-        Specifications::TextureSpecification spec         = {
-                    .Width        = width,
-                    .Height       = height,
-                    .BytePerPixel = Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)],
-                    .Format       = Specifications::ImageFormat::R8G8B8A8_SRGB,
-                    .Data         = image_data,
+        size_t                               data_size = width * height * Specifications::BytePerChannelMap[VALUE_FROM_SPEC_MAP(Specifications::ImageFormat::R8G8B8A8_SRGB)];
```
Comment (JeanPhilippeKernel) [inline ZEngine/ZEngine/Rendering/Renderers/GraphicRenderer.cpp]: same here, please simplify the expression.

**Review by JeanPhilippeKernel — CHANGES_REQUESTED** [review]

**Review by JeanPhilippeKernel — APPROVED** [review]
